"""Builds catalogue.json (the hand-picked film list) for the Film night app.
Each film: title, year, BBFC cert, minutes, moods, tags, intensity (1 gentle, 2 some tension, 3 intense),
flags (loud, flashing, scary, violence, sad, language, subtitles), note.
Certificates and runtimes are approximate; streaming is looked up live via JustWatch.
"""
import json, re

F = [
# ---- already seen (kept so "something like" works) ----
("Wonka",2023,"PG",116,"feelgood funny musical","musical fantasy chocolate whimsical dahl",1,"",""),
("The Mitchells vs. the Machines",2021,"PG",114,"animated funny adventure","robots family roadtrip ai",2,"loud flashing",""),
("Hidden Figures",2016,"PG",127,"truestory feelgood","space nasa history maths underdog",1,"",""),
("The Wild Robot",2024,"U",102,"animated heartfelt adventure","robots nature animals parenthood",2,"sad",""),
("WALL·E",2008,"U",98,"animated scifi heartfelt","robots space environment romance",1,"",""),
("Due Date",2010,"15",95,"funny","roadtrip buddy slapstick",2,"language",""),
("Big Hero 6",2014,"PG",102,"animated adventure funny","robots superhero grief science",2,"loud sad",""),
("Soul",2020,"PG",100,"animated heartfelt","music jazz afterlife life",1,"",""),
("Coco",2017,"PG",105,"animated heartfelt musical","music family mexico afterlife",2,"sad",""),
("The Sandlot",1993,"PG",101,"feelgood funny sport","baseball childhood friendship summer",1,"",""),
("The Princess Bride",1987,"PG",98,"adventure funny","fairytale romance swords quest",2,"",""),
("Monsters, Inc.",2001,"U",92,"animated funny","monsters friendship workplace",1,"",""),
("The Boy Who Harnessed the Wind",2019,"12A",113,"truestory heartfelt","africa engineering school invention underdog",2,"sad",""),
("Glass Onion: A Knives Out Mystery",2022,"12A",139,"mystery funny","whodunnit ensemble twist detective",2,"loud violence",""),
("Hunt for the Wilderpeople",2016,"12A",101,"funny adventure","new-zealand outsiders chase buddy",2,"flashing sad",""),
("The Martian",2015,"12A",144,"scifi thrilling","space survival science problem-solving nasa",2,"loud","One wince-making self-surgery scene"),
# ---- feel good and comedy ----
("Paddington",2014,"PG",95,"feelgood funny","london bear family british",1,"",""),
("Paddington 2",2017,"PG",103,"feelgood funny","london bear prison heist british",1,"",""),
("Paddington in Peru",2024,"PG",106,"feelgood funny adventure","bear jungle quest british family",1,"",""),
("School of Rock",2003,"PG",109,"funny feelgood musical","music band school underdog",1,"",""),
("Chef",2014,"15",114,"feelgood funny","food roadtrip father-son",1,"language",""),
("The Intern",2015,"12A",121,"feelgood funny","workplace friendship older",1,"",""),
("Yesterday",2019,"12A",116,"feelgood funny musical","music beatles romance fantasy british",1,"",""),
("Sing Street",2016,"12A",106,"feelgood heartfelt musical","music band school ireland 80s",1,"language",""),
("The Secret Life of Walter Mitty",2013,"PG",114,"feelgood adventure","travel daydream iceland sea",1,"",""),
("Jumanji: Welcome to the Jungle",2017,"12A",119,"funny adventure","videogame jungle body-swap teens",2,"loud violence",""),
("Free Guy",2021,"12A",115,"funny adventure","videogame ai romance",2,"loud flashing violence","Constant cartoonish game violence"),
("Night at the Museum",2006,"PG",108,"funny adventure","museum history magic",1,"",""),
("Elf",2003,"PG",97,"funny feelgood","christmas new-york fish-out-of-water",1,"",""),
("Groundhog Day",1993,"PG",101,"funny feelgood","timeloop romance small-town",1,"",""),
("Back to the Future",1985,"PG",116,"adventure funny scifi","timetravel 80s cars teen",2,"violence","A brief shooting"),
("Ferris Bueller's Day Off",1986,"15",103,"funny","school 80s chicago teen",1,"language",""),
("The Truman Show",1998,"PG",103,"scifi heartfelt","reality-tv satire sea mindbending",1,"",""),
("Big",1988,"PG",104,"funny feelgood","body-swap toys new-york",1,"",""),
("The Terminal",2004,"12A",128,"funny feelgood","airport immigrant friendship",1,"",""),
("Home Alone",1990,"PG",103,"funny","christmas slapstick burglars",1,"",""),
("The Parent Trap",1998,"PG",128,"funny feelgood","twins summer-camp london family",1,"",""),
("Freaky Friday",2003,"PG",97,"funny","body-swap mother-daughter teen music",1,"",""),
("Mrs. Doubtfire",1993,"12A",125,"funny heartfelt","divorce disguise family",1,"",""),
("Galaxy Quest",1999,"PG",102,"funny scifi","parody space actors aliens",2,"",""),
("Men in Black",1997,"PG",98,"funny scifi","aliens buddy new-york",2,"","Slimy alien gross-out moments"),
("Ghostbusters",1984,"PG",105,"funny","ghosts new-york 80s",2,"scary","Mild ghostly frights"),
("Bend It Like Beckham",2002,"12A",112,"feelgood funny sport","football british family culture",1,"",""),
("Cool Runnings",1993,"PG",98,"funny feelgood sport","bobsleigh jamaica olympics underdog",1,"",""),
("Eddie the Eagle",2016,"PG",106,"truestory feelgood sport","ski-jump olympics british underdog",1,"",""),
("Little Miss Sunshine",2006,"15",101,"funny heartfelt","roadtrip family pageant",1,"language",""),
("The Edge of Seventeen",2016,"15",104,"funny heartfelt","teen school friendship",1,"language",""),
("Lady Bird",2017,"15",94,"heartfelt funny","teen mother-daughter school",1,"language",""),
("Crazy Rich Asians",2018,"12A",120,"feelgood funny","romance singapore wedding family",1,"",""),
("Legally Blonde",2001,"12A",96,"funny feelgood","law underdog university",1,"",""),
("The Devil Wears Prada",2006,"PG",109,"funny","workplace fashion new-york",1,"",""),
("Clueless",1995,"12A",97,"funny","teen school 90s",1,"",""),
("Mean Girls",2004,"12A",97,"funny","teen school",1,"",""),
("Notting Hill",1999,"15",124,"funny feelgood","romance london british",1,"language",""),
("About Time",2013,"12A",123,"heartfelt funny","timetravel family romance british cornwall",1,"sad",""),
("Jojo Rabbit",2019,"12A",108,"funny heartfelt","ww2 satire germany",2,"sad violence","Dark turns late on"),
("Game Night",2018,"15",100,"funny thrilling mystery","party twist crime",2,"violence language",""),
("The Lost City",2022,"12A",112,"funny adventure","jungle romance treasure",2,"violence",""),
("Murder Mystery",2019,"12A",97,"funny mystery","whodunnit europe holiday",2,"violence",""),
("Catch Me If You Can",2002,"12A",141,"truestory funny thrilling","con chase 60s father-son",1,"",""),
("The Duke",2020,"12A",96,"truestory funny","heist art british",1,"",""),
("Fisherman's Friends",2019,"12A",112,"feelgood truestory musical","music cornwall sea band british",1,"language",""),
("Dream Horse",2020,"PG",113,"truestory feelgood sport","horses wales racing underdog",1,"",""),
("The Peanut Butter Falcon",2019,"12A",97,"heartfelt feelgood adventure","roadtrip river friendship wrestling",1,"language",""),
("Wonder",2017,"PG",113,"heartfelt feelgood","school difference family",1,"",""),
("Gifted",2017,"12A",101,"heartfelt","maths family custody",1,"sad",""),
("CODA",2021,"12A",111,"heartfelt feelgood musical","music family fishing coming-of-age",1,"language",""),
("The Intouchables",2011,"15",112,"truestory feelgood funny","friendship disability france",1,"language subtitles",""),
# ---- animated ----
("Zootropolis",2016,"PG",108,"animated funny mystery","animals detective city buddy",1,"",""),
("Ratatouille",2007,"U",111,"animated feelgood","food paris cooking underdog",1,"",""),
("Up",2009,"U",96,"animated adventure heartfelt","grief balloons old-age travel",1,"sad","A famously sad opening"),
("Inside Out",2015,"U",95,"animated heartfelt","emotions growing-up family",1,"sad",""),
("Inside Out 2",2024,"U",96,"animated heartfelt","emotions teen growing-up sport",1,"",""),
("Toy Story",1995,"U",81,"animated funny","toys friendship",1,"",""),
("Toy Story 3",2010,"U",103,"animated heartfelt","toys growing-up escape",2,"sad scary","A tense furnace scene"),
("Finding Nemo",2003,"U",100,"animated adventure","ocean fish parenthood sea",1,"",""),
("Moana",2016,"PG",107,"animated adventure musical","ocean sailing polynesia quest sea",2,"loud",""),
("Encanto",2021,"PG",102,"animated musical heartfelt","family colombia magic",1,"",""),
("Luca",2021,"U",95,"animated feelgood","italy summer friendship sea",1,"",""),
("Turning Red",2022,"PG",100,"animated funny","growing-up teen family music",1,"loud",""),
("Elemental",2023,"PG",101,"animated heartfelt","city romance immigrant family",1,"",""),
("Klaus",2019,"PG",97,"animated heartfelt funny","christmas postman friendship",1,"",""),
("Spider-Man: Into the Spider-Verse",2018,"PG",117,"animated thrilling","superhero multiverse teen",2,"loud flashing","Very busy, strobing visuals"),
("Spider-Man: Across the Spider-Verse",2023,"PG",140,"animated thrilling","superhero multiverse teen",2,"loud flashing","Very busy, strobing visuals"),
("How to Train Your Dragon",2010,"PG",98,"animated adventure","dragons vikings father-son",2,"loud",""),
("Kung Fu Panda",2008,"PG",92,"animated funny","martial-arts china underdog",1,"",""),
("Shrek",2001,"U",90,"animated funny","fairytale parody",1,"",""),
("The Incredibles",2004,"U",115,"animated thrilling funny","superhero family",2,"loud violence",""),
("Wallace & Gromit: The Curse of the Were-Rabbit",2005,"U",85,"animated funny","british claymation mystery",1,"",""),
("Wallace & Gromit: Vengeance Most Fowl",2024,"U",79,"animated funny","british claymation robots heist",1,"",""),
("Chicken Run",2000,"U",84,"animated funny","claymation escape british",1,"",""),
("Chicken Run: Dawn of the Nugget",2023,"U",101,"animated funny adventure","claymation heist spy british",1,"",""),
("Fantastic Mr. Fox",2009,"PG",87,"animated funny","heist wes-anderson animals dahl",1,"",""),
("Isle of Dogs",2018,"PG",101,"animated adventure","dogs japan wes-anderson",2,"",""),
("The Lego Movie",2014,"U",100,"animated funny","lego parody",1,"flashing",""),
("Robot Dreams",2023,"U",102,"animated heartfelt","robots friendship new-york",1,"sad","No dialogue at all"),
("The Bad Guys",2022,"U",100,"animated funny","heist animals",1,"",""),
("Puss in Boots: The Last Wish",2022,"U",102,"animated adventure funny","fairytale swords quest",2,"scary","A menacing villain"),
("Nimona",2023,"PG",101,"animated adventure","fantasy outsider knights",2,"violence",""),
("Spirited Away",2001,"PG",125,"animated adventure","fantasy japan ghibli",2,"scary","Some eerie creatures"),
("My Neighbour Totoro",1988,"U",86,"animated heartfelt","ghibli japan nature sisters",1,"",""),
("Kiki's Delivery Service",1989,"U",103,"animated feelgood","ghibli witch growing-up sea",1,"",""),
("The Iron Giant",1999,"U",86,"animated heartfelt","robots cold-war friendship",2,"sad",""),
("Onward",2020,"PG",102,"animated heartfelt adventure","brothers fantasy roadtrip grief",1,"sad",""),
("Leo",2023,"PG",102,"animated funny musical","school animals",1,"",""),
("Migration",2023,"U",83,"animated adventure","ducks travel family",1,"",""),
("The Super Mario Bros. Movie",2023,"U",92,"animated funny adventure","videogame",2,"loud flashing",""),
("Tangled",2010,"PG",100,"animated adventure musical","fairytale romance",1,"",""),
("Ron's Gone Wrong",2021,"PG",107,"animated funny heartfelt","robots school friendship phones",1,"loud",""),
# ---- mystery, heist, thrillers ----
("Enola Holmes",2020,"12",123,"mystery adventure","victorian detective teen-heroine london",2,"violence",""),
("Enola Holmes 2",2022,"12A",129,"mystery adventure","victorian detective teen-heroine london",2,"violence",""),
("Knives Out",2019,"12A",130,"mystery funny","whodunnit ensemble twist detective",2,"violence",""),
("See How They Run",2022,"12A",98,"mystery funny","whodunnit london theatre 50s detective",2,"violence",""),
("Murder on the Orient Express",2017,"12A",114,"mystery","whodunnit poirot train detective",2,"violence",""),
("Clue",1985,"PG",94,"mystery funny","whodunnit parody",1,"",""),
("The Sting",1973,"PG",129,"funny thrilling","con heist 1930s",1,"",""),
("Now You See Me",2013,"12A",115,"thrilling mystery","magic heist twist",2,"",""),
("Ocean's Eleven",2001,"12A",116,"thrilling funny","heist las-vegas ensemble",1,"",""),
("The Italian Job",1969,"PG",99,"funny thrilling","heist british cars",1,"",""),
("Sherlock Holmes",2009,"12A",128,"mystery thrilling funny","victorian detective london",2,"loud violence",""),
("Rear Window",1954,"PG",112,"mystery thrilling","hitchcock suspense",2,"",""),
("North by Northwest",1959,"PG",136,"thrilling","spy chase hitchcock",1,"",""),
("Hugo",2011,"U",126,"mystery adventure heartfelt","paris cinema automaton",1,"",""),
("National Treasure",2004,"PG",131,"adventure mystery","treasure history heist",1,"",""),
("Holes",2003,"PG",117,"adventure mystery","desert camp curse friendship",2,"",""),
("The Grand Budapest Hotel",2014,"15",99,"funny mystery","wes-anderson europe caper",2,"violence language","One brief grisly moment"),
("Operation Mincemeat",2021,"12A",128,"truestory thrilling","ww2 spy british",1,"",""),
("The Imitation Game",2014,"12A",114,"truestory thrilling","ww2 codebreaking maths british",2,"sad",""),
("Inception",2010,"12A",148,"thrilling scifi","dreams heist mindbending",2,"loud violence",""),
# ---- adventure, sci-fi, true stories, sport ----
("Indiana Jones and the Last Crusade",1989,"PG",127,"adventure funny","treasure father-son archaeology",2,"violence",""),
("Jurassic Park",1993,"PG",127,"thrilling adventure","dinosaurs science",3,"scary loud","Genuinely scary dinosaur attacks"),
("E.T. the Extra-Terrestrial",1982,"U",115,"heartfelt scifi","aliens friendship 80s",2,"sad",""),
("The Goonies",1985,"PG",114,"adventure funny","treasure 80s kids",2,"language",""),
("Stardust",2007,"PG",127,"adventure funny","fantasy romance witches",2,"violence",""),
("Pirates of the Caribbean: The Curse of the Black Pearl",2003,"12A",143,"adventure funny","pirates sailing sea",2,"scary violence loud","Skeleton pirates"),
("Master and Commander: The Far Side of the World",2003,"12A",138,"adventure thrilling","sailing navy sea napoleonic",2,"violence loud","Cannon battles, a shipboard operation"),
("Life of Pi",2012,"PG",127,"adventure heartfelt","sea tiger survival india",2,"sad",""),
("Kon-Tiki",2012,"12A",118,"truestory adventure","sailing raft ocean",2,"",""),
("Jungle Cruise",2021,"12A",127,"adventure funny","jungle amazon treasure",2,"loud",""),
("The Mummy",1999,"12A",124,"adventure funny","egypt treasure",2,"scary violence","Creepy scarab and mummy scenes"),
("Harry Potter and the Philosopher's Stone",2001,"PG",152,"adventure","fantasy magic school british",2,"",""),
("The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",2005,"PG",143,"adventure","fantasy ww2 siblings",2,"violence",""),
("The BFG",2016,"PG",117,"adventure heartfelt","giants dahl london",1,"",""),
("Matilda",1996,"PG",98,"funny","school fantasy books dahl",2,"",""),
("Matilda the Musical",2022,"PG",117,"musical funny","school fantasy books dahl british",2,"loud",""),
("Charlie and the Chocolate Factory",2005,"PG",115,"funny adventure","chocolate fantasy dahl whimsical",1,"",""),
("Apollo 13",1995,"PG",140,"truestory thrilling","space nasa survival problem-solving",2,"loud",""),
("October Sky",1999,"PG",108,"truestory heartfelt","rockets school space underdog",1,"",""),
("Interstellar",2014,"12A",169,"scifi heartfelt","space time father-daughter",2,"loud sad","Very long, very loud"),
("Arrival",2016,"12A",116,"scifi mystery","aliens language mindbending",2,"sad",""),
("Top Gun: Maverick",2022,"12A",131,"thrilling","planes military mentor",2,"loud",""),
("Ford v Ferrari",2019,"12A",152,"truestory thrilling sport","cars racing le-mans",2,"loud","One serious crash"),
("Real Steel",2011,"12A",127,"sport scifi","robots boxing father-son",2,"loud violence",""),
("Ready Player One",2018,"12A",140,"scifi adventure","videogame vr 80s",2,"loud flashing",""),
("Bumblebee",2018,"PG",114,"scifi adventure","robots 80s friendship cars",2,"loud",""),
("Remember the Titans",2000,"PG",113,"truestory sport feelgood","american-football race team",1,"",""),
("Chariots of Fire",1981,"PG",124,"truestory sport","running olympics british",1,"",""),
("Moneyball",2011,"12A",133,"truestory sport","baseball data underdog",1,"",""),
("Rocky",1976,"PG",120,"sport heartfelt","boxing underdog",2,"violence",""),
("The Karate Kid",1984,"PG",126,"sport feelgood","martial-arts mentor teen",2,"violence",""),
("The Dig",2021,"12A",112,"truestory heartfelt","archaeology suffolk british",1,"sad",""),
("Cast Away",2000,"12A",143,"adventure heartfelt","survival island sea",2,"sad","A painful tooth scene"),
("Forrest Gump",1994,"12A",142,"heartfelt funny","history america",2,"sad violence",""),
("Dead Poets Society",1989,"PG",128,"heartfelt","school poetry",2,"sad","A character's death"),
("Little Women",2019,"U",135,"heartfelt","sisters writing period",1,"sad",""),
("Pride & Prejudice",2005,"U",129,"heartfelt","romance period sisters british",1,"",""),
("Emma.",2020,"U",124,"funny","romance period british",1,"",""),
# ---- musicals and classics ----
("Hairspray",2007,"PG",117,"feelgood musical","dance 60s civil-rights",1,"",""),
("Mamma Mia!",2008,"PG",108,"feelgood musical funny","abba greece wedding sea",1,"",""),
("The Greatest Showman",2017,"PG",105,"feelgood musical","circus showbiz",1,"",""),
("Wicked",2024,"PG",160,"musical heartfelt","fantasy friendship witches",1,"","Long"),
("Singin' in the Rain",1952,"U",103,"musical funny feelgood","hollywood dance",1,"",""),
("Mary Poppins",1964,"U",139,"musical feelgood","london magic family",1,"",""),
("The Wizard of Oz",1939,"U",102,"musical adventure","fantasy quest",2,"scary","The witch can frighten"),
("Chitty Chitty Bang Bang",1968,"U",145,"musical adventure","cars fantasy",2,"scary","The Child Catcher"),
# ---- intense: hidden in gentle mode ----
("Gravity",2013,"12A",91,"thrilling scifi","space survival",3,"loud","Relentless peril"),
("Dunkirk",2017,"12A",106,"thrilling truestory","ww2 sea survival",3,"loud violence","Intense and very loud"),
("Dune",2021,"12A",155,"scifi thrilling","desert epic",3,"loud violence",""),
("Edge of Tomorrow",2014,"12A",113,"scifi thrilling","timeloop aliens war",3,"loud violence",""),
("Rush",2013,"15",123,"truestory thrilling sport","f1 racing rivalry",3,"loud violence","Graphic crash, sex scenes"),
("Coraline",2009,"PG",100,"animated mystery","fantasy",3,"scary","Genuinely creepy"),
("The Usual Suspects",1995,"18",106,"mystery thrilling","twist crime",3,"violence language",""),
]


# ---- grown-ups' nights (audience "adults") ----
ADULT = [
("Heat",1995,"15",170,"thrilling crime","heist la police",3,"violence loud",""),
("The Departed",2006,"18",151,"thrilling crime","police boston twist",3,"violence language",""),
("Prisoners",2013,"15",153,"thrilling mystery crime","kidnap detective",3,"violence","Harrowing"),
("Gone Girl",2014,"18",149,"thrilling mystery","twist marriage",3,"violence",""),
("Zodiac",2007,"15",157,"mystery truestory crime","detective journalism",2,"violence",""),
("Se7en",1995,"18",127,"thrilling mystery crime","detective",3,"violence scary",""),
("Nightcrawler",2014,"15",117,"thrilling crime","journalism la",2,"violence",""),
("Sicario",2015,"15",121,"thrilling crime","cartel",3,"violence",""),
("Hell or High Water",2016,"15",102,"thrilling crime","heist texas brothers",2,"violence",""),
("No Country for Old Men",2007,"15",122,"thrilling crime","texas chase",3,"violence",""),
("Fargo",1996,"18",98,"funny thrilling crime","snow dark-comedy",3,"violence",""),
("The Silence of the Lambs",1991,"18",118,"thrilling mystery crime","detective serial-killer",3,"violence scary",""),
("Memento",2000,"15",113,"mystery","mindbending twist crime",2,"violence",""),
("The Prestige",2006,"12A",130,"mystery","mindbending magic twist victorian",2,"",""),
("Shutter Island",2010,"15",138,"mystery thrilling","twist detective",3,"scary violence",""),
("Inside Man",2006,"15",129,"thrilling crime","heist new-york twist",2,"language",""),
("Baby Driver",2017,"15",113,"thrilling funny crime","heist music cars",2,"violence loud",""),
("Logan Lucky",2017,"12A",118,"funny crime","heist ensemble",1,"",""),
("The Nice Guys",2016,"15",116,"funny mystery crime","70s detective buddy la",2,"violence language",""),
("Snatch",2000,"18",104,"funny crime","london british ensemble",2,"violence language",""),
("Lock, Stock and Two Smoking Barrels",1998,"18",107,"funny crime","london british ensemble",2,"violence language",""),
("In Bruges",2008,"18",107,"funny heartfelt crime","belgium dark-comedy",2,"violence language",""),
("The Gentlemen",2019,"18",113,"funny crime","british london",2,"violence language",""),
("Wind River",2017,"15",107,"thrilling mystery crime","snow detective",3,"violence",""),
("The Talented Mr. Ripley",1999,"15",139,"thrilling mystery","italy con",2,"violence",""),
("Argo",2012,"15",120,"truestory thrilling","cia iran rescue",2,"language",""),
("Spotlight",2015,"15",129,"truestory mystery","journalism",1,"language","About church abuse cover-ups"),
("Bridge of Spies",2015,"12A",142,"truestory thrilling","cold-war spy lawyer",1,"",""),
("Tinker Tailor Soldier Spy",2011,"15",127,"mystery thrilling","spy cold-war british",2,"violence",""),
("The Bourne Identity",2002,"12A",119,"thrilling","spy chase europe",2,"violence",""),
("Mission: Impossible – Fallout",2018,"12A",147,"thrilling","spy action",2,"loud violence",""),
("Casino Royale",2006,"12A",144,"thrilling","spy bond",2,"violence",""),
("Skyfall",2012,"12A",143,"thrilling","spy bond british",2,"violence loud",""),
("Mad Max: Fury Road",2015,"15",120,"thrilling","desert chase",3,"loud violence",""),
("The Dark Knight",2008,"12A",152,"thrilling crime","superhero",3,"violence loud",""),
("Oppenheimer",2023,"15",180,"truestory","history science ww2",2,"loud","Three hours"),
("Blade Runner 2049",2017,"15",164,"scifi mystery","ai",2,"violence",""),
("Ex Machina",2014,"15",108,"scifi mystery","robots ai",2,"",""),
("The Matrix",1999,"15",136,"scifi thrilling","mindbending ai",3,"violence",""),
("Everything Everywhere All at Once",2022,"15",139,"scifi funny heartfelt","multiverse family",2,"flashing",""),
("Eternal Sunshine of the Spotless Mind",2004,"15",108,"scifi heartfelt","romance mindbending",1,"",""),
("Her",2013,"15",126,"heartfelt scifi","ai romance",1,"",""),
("District 9",2009,"15",112,"scifi thrilling","aliens",3,"violence",""),
("Moon",2009,"15",97,"scifi mystery","space",1,"",""),
("The Shawshank Redemption",1994,"15",142,"heartfelt","prison friendship",2,"violence",""),
("Good Will Hunting",1997,"15",126,"heartfelt","maths friendship",1,"language",""),
("The King's Speech",2010,"12A",118,"truestory heartfelt","royals british friendship",1,"language",""),
("The Social Network",2010,"12A",120,"truestory","tech startup",1,"",""),
("The Big Short",2015,"15",130,"truestory funny","finance",1,"language",""),
("Whiplash",2014,"15",107,"thrilling heartfelt","music jazz mentor",2,"language",""),
("La La Land",2016,"12A",128,"musical heartfelt","romance la jazz",1,"",""),
("Green Book",2018,"12A",130,"truestory heartfelt","roadtrip music friendship",1,"",""),
("Parasite",2019,"15",132,"thrilling funny","class twist korea",3,"violence subtitles",""),
("The Lives of Others",2006,"15",137,"thrilling heartfelt","stasi germany spy",2,"subtitles",""),
("Good Bye Lenin!",2003,"15",121,"funny heartfelt","germany berlin family",1,"subtitles",""),
("Das Boot",1981,"15",149,"thrilling","ww2 submarine sea germany",3,"loud violence subtitles",""),
("Run Lola Run",1998,"15",81,"thrilling","germany berlin timeloop",2,"subtitles",""),
("Amélie",2001,"15",122,"feelgood funny","paris romance",1,"subtitles",""),
("Cinema Paradiso",1988,"PG",155,"heartfelt","italy cinema",1,"subtitles",""),
("The Banshees of Inisherin",2022,"15",114,"funny heartfelt","ireland friendship dark-comedy",2,"violence",""),
("Three Billboards Outside Ebbing, Missouri",2017,"15",115,"funny heartfelt crime","small-town grief",3,"violence language",""),
("The Holdovers",2023,"15",133,"funny heartfelt","school christmas 70s",1,"language",""),
("Sideways",2004,"15",127,"funny","roadtrip wine friendship",1,"language",""),
("Lost in Translation",2003,"15",102,"heartfelt","japan friendship",1,"",""),
("Before Sunrise",1995,"15",101,"heartfelt","romance europe",1,"",""),
("Past Lives",2023,"12A",105,"heartfelt","romance korea new-york",1,"",""),
("Brooklyn",2015,"12A",112,"heartfelt","romance immigrant ireland new-york",1,"",""),
("The Remains of the Day",1993,"U",134,"heartfelt","british period",1,"",""),
("Pride",2014,"15",120,"truestory funny heartfelt","british miners 80s",1,"language",""),
("The Full Monty",1997,"15",91,"funny","british sheffield",1,"language",""),
("Four Weddings and a Funeral",1994,"15",117,"funny","british romance weddings",1,"language",""),
("Hot Fuzz",2007,"15",121,"funny thrilling","british police village",2,"violence",""),
("Shaun of the Dead",2004,"15",99,"funny","british zombies",3,"scary violence",""),
("Local Hero",1983,"PG",111,"funny feelgood","scotland village sea",1,"",""),
("Calendar Girls",2003,"12A",108,"truestory funny","british",1,"",""),
("Philomena",2013,"12A",98,"truestory heartfelt","british ireland journalism",1,"",""),
("Belfast",2021,"12A",98,"heartfelt","childhood northern-ireland 60s",2,"violence",""),
("Planes, Trains and Automobiles",1987,"15",93,"funny","roadtrip buddy",1,"language",""),
("The Blues Brothers",1980,"15",133,"funny musical","chicago cars",1,"",""),
("Airplane!",1980,"PG",88,"funny","parody planes",1,"",""),
("This Is Spinal Tap",1984,"15",82,"funny","music band mockumentary",1,"language",""),
("Some Like It Hot",1959,"PG",121,"funny","romance disguise",1,"",""),
("Casablanca",1942,"U",102,"heartfelt","romance ww2",1,"",""),
("The Godfather",1972,"18",175,"thrilling crime","mafia family",3,"violence",""),
("Goodfellas",1990,"18",145,"thrilling crime","mafia",3,"violence language",""),
("Jaws",1975,"12A",124,"thrilling","sea shark beach",3,"scary",""),
("The Perfect Storm",2000,"12A",130,"truestory thrilling","sea fishing storm",3,"loud sad",""),
("All Is Lost",2013,"12A",106,"thrilling","sailing survival sea",2,"",""),
("Captain Phillips",2013,"12A",134,"truestory thrilling","sea pirates navy",3,"violence",""),
("Greyhound",2020,"12A",91,"thrilling","ww2 navy sea",2,"loud",""),
("The Boat That Rocked",2009,"15",135,"funny","music sea 60s british",1,"language",""),
("Senna",2010,"12A",106,"truestory sport","f1 racing documentary",1,"sad",""),
("Free Solo",2018,"12A",100,"truestory thrilling","climbing documentary",2,"",""),
("Dune: Part Two",2024,"12A",166,"scifi thrilling","desert epic",3,"loud violence",""),
("Gladiator",2000,"15",155,"thrilling adventure","rome epic",3,"violence",""),
("Saving Private Ryan",1998,"15",169,"thrilling","ww2 war",3,"violence loud",""),
("The Great Escape",1963,"PG",172,"adventure truestory","ww2 escape",1,"",""),
("Conclave",2024,"12A",120,"mystery thrilling","vatican election",1,"",""),
("Anatomy of a Fall",2023,"15",151,"mystery","courtroom france",1,"language subtitles",""),
("A Few Good Men",1992,"15",138,"thrilling","courtroom military",1,"language",""),
("12 Angry Men",1957,"U",96,"thrilling","courtroom",1,"",""),
("Top Gun",1986,"15",110,"thrilling","planes",1,"",""),
("Die Hard",1988,"18",132,"thrilling","christmas action",3,"violence language",""),
]

SEEN = {  # who has seen it, as far as we know; "Family" = the household
 "Wonka":"Family","The Mitchells vs. the Machines":"Family","Hidden Figures":"Dad","The Wild Robot":"Family",
 "WALL·E":"Family","Due Date":"Family","Big Hero 6":"Family","Soul":"Family","Coco":"Family","The Sandlot":"Family",
 "The Princess Bride":"Family","Monsters, Inc.":"Family","The Boy Who Harnessed the Wind":"Family",
 "Glass Onion: A Knives Out Mystery":"Family","Hunt for the Wilderpeople":"Family","The Martian":"Family",
 "Forrest Gump":"Family","Matilda":"Family","The Goonies":"Family",
}

def slug(t,y): return re.sub(r"[^a-z0-9]+","-",t.lower()).strip("-")+f"-{y}"
films, seen = [], []
def audience(c, moods, adult):
    if adult or c in ("15","18"): return "adults"
    if c in ("U","PG") and "animated" in moods: return "kids"
    return "family"
for (t,y,c,m,moods,tags,i,flags,note),adult in [(x,False) for x in F]+[(x,True) for x in ADULT]:
    fid = slug(t,y)
    films.append({"id":fid,"t":t,"y":y,"c":c,"r":m,"m":moods.split(),"g":tags.split(),"i":i,
                  "f":flags.split(),"n":note,"a":audience(c,moods.split(),adult)})
    if t in SEEN: seen.append({"id":fid,"who":[SEEN[t]]})
assert len({f["id"] for f in films})==len(films)
assert all(t in {f["t"] for f in films} for t in SEEN)
import os
root = os.path.dirname(os.path.abspath(__file__))
cat = {"updated":"2026-09-27","films":films,"seen":seen}
json.dump(cat, open(os.path.join(root,"catalogue.json"),"w"), ensure_ascii=False, indent=1)
# films.json is normally rebuilt by refresh.py; write a plain copy so the app works before the first refresh
if not os.path.exists(os.path.join(root,"films.json")) or os.environ.get("RESET_FILMS"):
    json.dump(cat, open(os.path.join(root,"films.json"),"w"), ensure_ascii=False, separators=(",",":"))
print(len(films),"films,",len(seen),"seen,",sum(f["i"]<3 for f in films),"shown in gentle mode")
